// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: create_todo.sql

package db

import (
	"context"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (title, done)
VALUES ($1, $2)
RETURNING id, title, done
`

type CreateTodoParams struct {
	Title string
	Done  bool
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, createTodo, arg.Title, arg.Done)
	var i Todo
	err := row.Scan(&i.ID, &i.Title, &i.Done)
	return i, err
}
