// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: update_todo.sql

package db

import (
	"context"
)

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos
SET title = $2, done = $3
WHERE id = $1
RETURNING id, title, done
`

type UpdateTodoParams struct {
	ID    int32
	Title string
	Done  bool
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, updateTodo, arg.ID, arg.Title, arg.Done)
	var i Todo
	err := row.Scan(&i.ID, &i.Title, &i.Done)
	return i, err
}
